### ISSUE TITLE
If i want to learn more about MSR,which articles I should read

### ISSUE THREAD

**Issue by Fatigerrr** [99taeha/STRAP#1]
Hello sir，If i want to learn more about MSR,which articles I should read，Thanks for you reply

**Comment by 99taeha** [comment]
I apologize for the late response.
I suggest you read the paper "Matrix-based system reliability method and applications to bridge networks".

**Comment by Fatigerrr** [comment]
> 

Thank you,here i have a new question about the code, when i set 
distribution_dataset = [[2,220,220*0.11,220],[1,235,235*0.05,235],]
correlation_xx = 1*np.eye(2)
Then try to calculate the system failure probability
But the

**Comment by Fatigerrr** [comment]
Thank you,here i have a new question about the code, when i set
distribution_dataset = [[2,220,2200.11,220],[1,235,2350.05,235],]
correlation_xx = 1*np.eye(2)
Then try to calculate the system failure probability
But the code will report an error
**“numpy.linalg.LinAlgError: Matrix is not positive definite”**
I want to ask you why this kind of problem occurs
I also sent an email to your Google mailbox explaining the problem,
 thank you very much

**Comment by 99taeha** [comment]
Can you give me other information for input file?

**Comment by 99taeha** [comment]
Can you give me more information about your input file?
You can send the input file to my email.
